# This file was generated by SquareLine Studio
# SquareLine Studio version: SquareLine Studio 1.4.0
# LVGL version: 8.3.11
# Project name: SquareLine_Project

import lvgl as lv
import ui_images

dispp = lv.disp_get_default()
theme = lv.theme_default_init(dispp, lv.palette_main(lv.PALETTE.BLUE), lv.palette_main(lv.PALETTE.RED), True, lv.font_default())
dispp.set_theme(theme)

font_F1R14 = lv.font_load("A:ui_font_F1R14.bin")
font_F1R10 = lv.font_load("A:ui_font_F1R10.bin")
font_F1B18 = lv.font_load("A:ui_font_F1B18.bin")
font_F1B22 = lv.font_load("A:ui_font_F1B22.bin")
font_DISPLAYB14 = lv.font_load("A:ui_font_DISPLAYB14.bin")
font_DISPLAYM10 = lv.font_load("A:ui_font_DISPLAYM10.bin")
font_F1R12 = lv.font_load("A:ui_font_F1R12.bin")
font_DISPLAYR60 = lv.font_load("A:ui_font_DISPLAYR60.bin")
font_DISPLAYM14 = lv.font_load("A:ui_font_DISPLAYM14.bin")
font_DISPLAYR30 = lv.font_load("A:ui_font_DISPLAYR30.bin")
font_DISPLAYB80 = lv.font_load("A:ui_font_DISPLAYB80.bin")
font_DISPLAYM24 = lv.font_load("A:ui_font_DISPLAYM24.bin")
font_DISPLAYM18 = lv.font_load("A:ui_font_DISPLAYM18.bin")

def ui_theme_set(idx):
   return

def SetFlag( obj, flag, value):
    if (value):
        obj.add_flag(flag)
    else:
        obj.clear_flag(flag)
    return

_ui_comp_table = {}
_ui_comp_prev = None
_ui_name_prev = None
_ui_child_prev = None
_ui_comp_table.clear()

def _ui_comp_del_event(e):
    target = e.get_target()
    _ui_comp_table[id(target)].remove()

def ui_comp_get_child(comp, child_name):
    return _ui_comp_table[id(comp)][child_name]

def ui_comp_get_root_from_child(child, compname):
    for component in _ui_comp_table:
        if _ui_comp_table[component]["_CompName"]==compname:
            for part in _ui_comp_table[component]:
                if id(_ui_comp_table[component][part]) == id(child):
                    return _ui_comp_table[component]
    return None
def SetBarProperty(target, id, val):
   if id == 'Value_with_anim': target.set_value(val, lv.ANIM.ON)
   if id == 'Value': target.set_value(val, lv.ANIM.OFF)
   return

def SetPanelProperty(target, id, val):
   if id == 'Position_X': target.set_x(val)
   if id == 'Position_Y': target.set_y(val)
   if id == 'Width': target.set_width(val)
   if id == 'Height': target.set_height(val)
   return

def SetDropdownProperty(target, id, val):
   if id == 'Selected':
      target.set_selected(val)
   return

def SetImageProperty(target, id, val, val2):
   if id == 'Image': target.set_src(val)
   if id == 'Angle': target.set_angle(val2)
   if id == 'Zoom': target.set_zoom(val2)
   return

def SetLabelProperty(target, id, val):
   if id == 'Text': target.set_text(val)
   return

def SetRollerProperty(target, id, val):
   if id == 'Selected':
      target.set_selected(val, lv.ANIM.OFF)
   if id == 'Selected_with_anim':
      target.set_selected(val, lv.ANIM.ON)
   return

def SetSliderProperty(target, id, val):
   if id == 'Value_with_anim': target.set_value(val, lv.ANIM.ON)
   if id == 'Value': target.set_value(val, lv.ANIM.OFF)
   return

def ChangeScreen( src, fademode, speed, delay):
    lv.scr_load_anim(src, fademode, speed, delay, False)
    return

def DeleteScreen(src):
    return

def IncrementArc( trg, val):
    trg.set_value(trg.get_value()+val)
    lv.event_send(trg,lv.EVENT.VALUE_CHANGED, None)
    return

def IncrementBar( trg, val, anim):
    trg.set_value(trg.get_value()+val,anim)
    return

def IncrementSlider( trg, val, anim):
    trg.set_value(trg.get_value()+val,anim)
    lv.event_send(trg,lv.EVENT.VALUE_CHANGED, None)
    return

def KeyboardSetTarget( keyboard, textarea):
    keyboard.set_textarea(textarea)
    return

def ModifyFlag( obj, flag, value):
    if (value=="TOGGLE"):
        if ( obj.has_flag(flag) ):
            obj.clear_flag(flag)
        else:
            obj.add_flag(flag)
        return

    if (value=="ADD"):
        obj.add_flag(flag)
    else:
        obj.clear_flag(flag)
    return

def ModifyState( obj, state, value):
    if (value=="TOGGLE"):
        if ( obj.has_state(state) ):
            obj.clear_state(state)
        else:
            obj.add_state(state)
        return

    if (value=="ADD"):
        obj.add_state(state)
    else:
        obj.clear_state(state)
    return

def TextAreaMoveCursor( trg, val):
    if val=="UP" : trg.cursor_up()
    if val=="RIGHT" : trg.cursor_right()
    if val=="DOWN" : trg.cursor_down()
    if val=="LEFT" : trg.cursor_left()
    trg.add_state(lv.STATE.FOCUSED)
    return

def set_opacity(obj, v):
    obj.set_style_opa(v, lv.STATE.DEFAULT|lv.PART.MAIN)
    return

def SetTextValueArc( trg, src, prefix, postfix):
    trg.set_text(prefix+str(src.get_value())+postfix)
    return

def SetTextValueSlider( trg, src, prefix, postfix):
    trg.set_text(prefix+str(src.get_value())+postfix)
    return

def SetTextValueChecked( trg, src, txton, txtoff):
    if src.has_state(lv.STATE.CHECKED):
        trg.set_text(txton)
    else:
        trg.set_text(txtoff)
    return

def StepSpinbox( trg, val):
    if val==1 : trg.increment()
    if val==-1 : trg.decrement()
    lv.event_send(trg,lv.EVENT.VALUE_CHANGED, None)
    return

def SwitchTheme(val):
    ui_theme_set(val)
    return

def Flash_Animation(TargetObject, delay):
  PropertyAnimation_0 = lv.anim_t()
  PropertyAnimation_0.init()
  PropertyAnimation_0.set_path_cb(lv.anim_t.path_ease_out)
  PropertyAnimation_0.set_time(1000)
  PropertyAnimation_0.set_var(TargetObject)
  PropertyAnimation_0.set_custom_exec_cb(lambda a, v: TargetObject.set_style_opa(v,0))
  PropertyAnimation_0.set_delay(delay + 0)
  PropertyAnimation_0.set_repeat_count(lv.ANIM_REPEAT.INFINITE)
  PropertyAnimation_0.set_repeat_delay(0) #+ 1000
  PropertyAnimation_0.set_playback_delay(0)
  PropertyAnimation_0.set_playback_time(1000)
  PropertyAnimation_0.set_early_apply(False)
  PropertyAnimation_0.set_values(255, 100)
  lv.anim_t.start(PropertyAnimation_0)

  print ("Flash_Animation called")
  return

# COMPONENTS
ui____initial_actions0 = lv.obj()

ui_MsgScreen = lv.obj()
SetFlag(ui_MsgScreen, lv.obj.FLAG.SCROLLABLE, False)
ui_MsgScreen.set_style_bg_color(lv.color_hex(0x000000), lv.PART.MAIN | lv.STATE.DEFAULT )
ui_MsgScreen.set_style_bg_opa(255, lv.PART.MAIN| lv.STATE.DEFAULT )

ui_Team_Label = lv.label(ui_MsgScreen)
ui_Team_Label.set_text("Mercedes")
ui_Team_Label.set_width(lv.SIZE.CONTENT)	# 1
ui_Team_Label.set_height(lv.SIZE.CONTENT)   # 1
ui_Team_Label.set_x(-1)
ui_Team_Label.set_y(lv.pct(12))
ui_Team_Label.set_align( lv.ALIGN.TOP_MID)
ui_Team_Label.set_style_text_font( font_F1R14, lv.PART.MAIN | lv.STATE.DEFAULT )

ui_Team_Color_Container = lv.obj(ui_MsgScreen)
ui_Team_Color_Container.remove_style_all()
ui_Team_Color_Container.set_width(105)
ui_Team_Color_Container.set_height(3)
ui_Team_Color_Container.set_x(67)
ui_Team_Color_Container.set_y(19)
SetFlag(ui_Team_Color_Container, lv.obj.FLAG.CLICKABLE, False)
SetFlag(ui_Team_Color_Container, lv.obj.FLAG.SCROLLABLE, False)
ui_Team_Color_Container.set_style_bg_color(lv.color_hex(0xFF0000), lv.PART.MAIN | lv.STATE.DEFAULT )
ui_Team_Color_Container.set_style_bg_opa(255, lv.PART.MAIN| lv.STATE.DEFAULT )

ui_wave_Container = lv.obj(ui_MsgScreen)
ui_wave_Container.remove_style_all()
ui_wave_Container.set_width(178)
ui_wave_Container.set_height(44)
ui_wave_Container.set_x(0)
ui_wave_Container.set_y(-50)
ui_wave_Container.set_align( lv.ALIGN.CENTER)
SetFlag(ui_wave_Container, lv.obj.FLAG.CLICKABLE, False)
SetFlag(ui_wave_Container, lv.obj.FLAG.SCROLLABLE, False)

ui_Msg_Container = lv.obj(ui_MsgScreen)
ui_Msg_Container.remove_style_all()
ui_Msg_Container.set_width(193)
ui_Msg_Container.set_height(163)
ui_Msg_Container.set_x(32)
ui_Msg_Container.set_y(48)
SetFlag(ui_Msg_Container, lv.obj.FLAG.CLICKABLE, False)
SetFlag(ui_Msg_Container, lv.obj.FLAG.SCROLLABLE, False)

ui_Team_Color_Container2 = lv.obj(ui_Msg_Container)
ui_Team_Color_Container2.remove_style_all()
ui_Team_Color_Container2.set_width(5)
ui_Team_Color_Container2.set_height(25)
ui_Team_Color_Container2.set_x(7)
ui_Team_Color_Container2.set_y(54)
SetFlag(ui_Team_Color_Container2, lv.obj.FLAG.CLICKABLE, False)
SetFlag(ui_Team_Color_Container2, lv.obj.FLAG.SCROLLABLE, False)
ui_Team_Color_Container2.set_style_bg_color(lv.color_hex(0x00CCB7), lv.PART.MAIN | lv.STATE.DEFAULT )
ui_Team_Color_Container2.set_style_bg_opa(255, lv.PART.MAIN| lv.STATE.DEFAULT )
ui_Team_Color_Container2.set_style_shadow_color(lv.color_hex(0x00CCB7), lv.PART.MAIN | lv.STATE.DEFAULT )
ui_Team_Color_Container2.set_style_shadow_opa(255, lv.PART.MAIN| lv.STATE.DEFAULT )
ui_Team_Color_Container2.set_style_shadow_width( 3, lv.PART.MAIN | lv.STATE.DEFAULT )
ui_Team_Color_Container2.set_style_shadow_spread( 0, lv.PART.MAIN | lv.STATE.DEFAULT )
ui_Team_Color_Container2.set_style_shadow_ofs_x( 0, lv.PART.MAIN | lv.STATE.DEFAULT )
ui_Team_Color_Container2.set_style_shadow_ofs_y( 0, lv.PART.MAIN | lv.STATE.DEFAULT )

ui_Customer_Person = lv.img(ui_Msg_Container)
ui_Customer_Person.set_src(ui_images.ui_img_loading_person_png)
ui_Customer_Person.set_width(lv.SIZE.CONTENT)	# 1
ui_Customer_Person.set_height(lv.SIZE.CONTENT)   # 1
ui_Customer_Person.set_x(63)
ui_Customer_Person.set_y(42)
ui_Customer_Person.set_align( lv.ALIGN.CENTER)
SetFlag(ui_Customer_Person, lv.obj.FLAG.ADV_HITTEST, True)
SetFlag(ui_Customer_Person, lv.obj.FLAG.SCROLLABLE, False)
ui_Customer_Person.set_zoom(235)

ui_Msg_Label = lv.label(ui_Msg_Container)
ui_Msg_Label.set_text("\"I CAN'T BELIEVE YOU GUYS *** *** ME. CAN'T TELL YOU HOW **** *I AM\"")
ui_Msg_Label.set_width(134)
ui_Msg_Label.set_height(54)
ui_Msg_Label.set_x(7)
ui_Msg_Label.set_y(93)
ui_Msg_Label.set_style_text_color(lv.color_hex(0x00CCB7), lv.PART.MAIN | lv.STATE.DEFAULT )
ui_Msg_Label.set_style_text_opa(255, lv.PART.MAIN| lv.STATE.DEFAULT )
ui_Msg_Label.set_style_text_letter_space( 0, lv.PART.MAIN | lv.STATE.DEFAULT )
ui_Msg_Label.set_style_text_line_space( 3, lv.PART.MAIN | lv.STATE.DEFAULT )
ui_Msg_Label.set_style_text_align( lv.TEXT_ALIGN.LEFT, lv.PART.MAIN | lv.STATE.DEFAULT )
ui_Msg_Label.set_style_text_font( font_F1R10, lv.PART.MAIN | lv.STATE.DEFAULT )

ui_Driver_Label = lv.label(ui_Msg_Container)
ui_Driver_Label.set_text("HAM")
ui_Driver_Label.set_width(lv.SIZE.CONTENT)	# 1
ui_Driver_Label.set_height(lv.SIZE.CONTENT)   # 1
ui_Driver_Label.set_x(20)
ui_Driver_Label.set_y(57)
ui_Driver_Label.set_style_text_font( font_F1B18, lv.PART.MAIN | lv.STATE.DEFAULT )

ui_EmoilScreen = lv.obj()
SetFlag(ui_EmoilScreen, lv.obj.FLAG.SCROLLABLE, False)
ui_EmoilScreen.set_style_bg_color(lv.color_hex(0x0A00A9), lv.PART.MAIN | lv.STATE.DEFAULT )
ui_EmoilScreen.set_style_bg_opa(255, lv.PART.MAIN| lv.STATE.DEFAULT )
ui_EmoilScreen.set_style_bg_grad_color(lv.color_hex(0x000000), lv.PART.MAIN | lv.STATE.DEFAULT )
ui_EmoilScreen.set_style_bg_main_stop( 0, lv.PART.MAIN | lv.STATE.DEFAULT )
ui_EmoilScreen.set_style_bg_grad_stop( 255, lv.PART.MAIN | lv.STATE.DEFAULT )
ui_EmoilScreen.set_style_bg_grad_dir( lv.GRAD_DIR.VER, lv.PART.MAIN | lv.STATE.DEFAULT )
ui_EmoilScreen.set_style_bg_img_src( ui_images.ui_img_grid_png, lv.PART.MAIN | lv.STATE.DEFAULT )

ui_EmoilScreen_Image1 = lv.img(ui_EmoilScreen)
ui_EmoilScreen_Image1.set_src(ui_images.ui_img_helmet_redbull_png)
ui_EmoilScreen_Image1.set_width(lv.SIZE.CONTENT)	# 1
ui_EmoilScreen_Image1.set_height(lv.SIZE.CONTENT)   # 1
ui_EmoilScreen_Image1.set_align( lv.ALIGN.CENTER)
SetFlag(ui_EmoilScreen_Image1, lv.obj.FLAG.ADV_HITTEST, True)
SetFlag(ui_EmoilScreen_Image1, lv.obj.FLAG.SCROLLABLE, False)

ui_EmoilScreen_Container1 = lv.obj(ui_EmoilScreen)
ui_EmoilScreen_Container1.remove_style_all()
ui_EmoilScreen_Container1.set_width(150)
ui_EmoilScreen_Container1.set_height(80)
ui_EmoilScreen_Container1.set_x(0)
ui_EmoilScreen_Container1.set_y(15)
ui_EmoilScreen_Container1.set_align( lv.ALIGN.CENTER)
SetFlag(ui_EmoilScreen_Container1, lv.obj.FLAG.CLICKABLE, False)
SetFlag(ui_EmoilScreen_Container1, lv.obj.FLAG.SCROLLABLE, False)

def FlashScreen_eventhandler(event_struct):
   event = event_struct.code
   if event == lv.EVENT.SCREEN_LOADED and True:
      Flash_Animation(ui_Flash_Label5, 100)
   return

ui_FlashScreen = lv.obj()
SetFlag(ui_FlashScreen, lv.obj.FLAG.SCROLLABLE, False)
ui_FlashScreen.set_style_bg_color(lv.color_hex(0x000000), lv.PART.MAIN | lv.STATE.DEFAULT )
ui_FlashScreen.set_style_bg_opa(255, lv.PART.MAIN| lv.STATE.DEFAULT )

ui_Flash_Label5 = lv.label(ui_FlashScreen)
ui_Flash_Label5.set_text("SPEED IMPRINT")
ui_Flash_Label5.set_width(lv.SIZE.CONTENT)	# 1
ui_Flash_Label5.set_height(lv.SIZE.CONTENT)   # 1
ui_Flash_Label5.set_align( lv.ALIGN.CENTER)
ui_Flash_Label5.set_style_text_font( font_F1B22, lv.PART.MAIN | lv.STATE.DEFAULT )

ui_FlashScreen.add_event_cb(FlashScreen_eventhandler, lv.EVENT.ALL, None)

ui_ScheduleScreen = lv.obj()
SetFlag(ui_ScheduleScreen, lv.obj.FLAG.SCROLLABLE, False)
ui_ScheduleScreen.set_style_bg_color(lv.color_hex(0x000000), lv.PART.MAIN | lv.STATE.DEFAULT )
ui_ScheduleScreen.set_style_bg_opa(255, lv.PART.MAIN| lv.STATE.DEFAULT )
ui_ScheduleScreen.set_style_bg_img_opa( 255, lv.PART.MAIN | lv.STATE.DEFAULT )

ui_Second_Arc = lv.arc(ui_ScheduleScreen)
ui_Second_Arc.set_width(230)
ui_Second_Arc.set_height(230)
ui_Second_Arc.set_align( lv.ALIGN.CENTER)
ui_Second_Arc.set_range(0,60)
ui_Second_Arc.set_value(45)
ui_Second_Arc.set_bg_angles(0,360)
ui_Second_Arc.set_rotation(-90)
ui_Second_Arc.set_style_arc_color(lv.color_hex(0xFFFFFF), lv.PART.MAIN | lv.STATE.DEFAULT )
ui_Second_Arc.set_style_arc_opa(0, lv.PART.MAIN| lv.STATE.DEFAULT )
ui_Second_Arc.set_style_arc_width( 3, lv.PART.MAIN | lv.STATE.DEFAULT )

ui_Second_Arc.set_style_arc_color(lv.color_hex(0xFFDD00), lv.PART.INDICATOR | lv.STATE.DEFAULT )
ui_Second_Arc.set_style_arc_opa(255, lv.PART.INDICATOR| lv.STATE.DEFAULT )
ui_Second_Arc.set_style_arc_width( 2, lv.PART.INDICATOR | lv.STATE.DEFAULT )
ui_Second_Arc.set_style_arc_rounded( True, lv.PART.INDICATOR | lv.STATE.DEFAULT )

ui_Second_Arc.set_style_opa( 0, lv.PART.KNOB | lv.STATE.DEFAULT )

ui_Upcoming_Label = lv.label(ui_ScheduleScreen)
ui_Upcoming_Label.set_text("Upcoming")
ui_Upcoming_Label.set_width(lv.SIZE.CONTENT)	# 1
ui_Upcoming_Label.set_height(lv.SIZE.CONTENT)   # 1
ui_Upcoming_Label.set_x(0)
ui_Upcoming_Label.set_y(20)
ui_Upcoming_Label.set_align( lv.ALIGN.TOP_MID)
ui_Upcoming_Label.set_style_text_color(lv.color_hex(0x8D8D8D), lv.PART.MAIN | lv.STATE.DEFAULT )
ui_Upcoming_Label.set_style_text_opa(255, lv.PART.MAIN| lv.STATE.DEFAULT )
ui_Upcoming_Label.set_style_text_font( font_DISPLAYB14, lv.PART.MAIN | lv.STATE.DEFAULT )

ui_Gmt_Label = lv.label(ui_ScheduleScreen)
ui_Gmt_Label.set_text("UTC/GMT +8")
ui_Gmt_Label.set_width(lv.SIZE.CONTENT)	# 1
ui_Gmt_Label.set_height(lv.SIZE.CONTENT)   # 1
ui_Gmt_Label.set_x(0)
ui_Gmt_Label.set_y(-80)
ui_Gmt_Label.set_align( lv.ALIGN.BOTTOM_MID)
ui_Gmt_Label.set_style_text_color(lv.color_hex(0x9E9E9E), lv.PART.MAIN | lv.STATE.DEFAULT )
ui_Gmt_Label.set_style_text_opa(255, lv.PART.MAIN| lv.STATE.DEFAULT )
ui_Gmt_Label.set_style_text_letter_space( 0, lv.PART.MAIN | lv.STATE.DEFAULT )
ui_Gmt_Label.set_style_text_line_space( 0, lv.PART.MAIN | lv.STATE.DEFAULT )
ui_Gmt_Label.set_style_text_font( font_DISPLAYM10, lv.PART.MAIN | lv.STATE.DEFAULT )

ui_Session_Label = lv.label(ui_ScheduleScreen)
ui_Session_Label.set_text("Canadian Grand Prix")
ui_Session_Label.set_width(lv.SIZE.CONTENT)	# 1
ui_Session_Label.set_height(lv.SIZE.CONTENT)   # 1
ui_Session_Label.set_x(0)
ui_Session_Label.set_y(51)
ui_Session_Label.set_align( lv.ALIGN.CENTER)
ui_Session_Label.set_style_text_color(lv.color_hex(0xFFDD00), lv.PART.MAIN | lv.STATE.DEFAULT )
ui_Session_Label.set_style_text_opa(255, lv.PART.MAIN| lv.STATE.DEFAULT )
ui_Session_Label.set_style_text_align( lv.TEXT_ALIGN.CENTER, lv.PART.MAIN | lv.STATE.DEFAULT )
ui_Session_Label.set_style_text_font( font_F1R12, lv.PART.MAIN | lv.STATE.DEFAULT )

ui_Event_Label = lv.label(ui_ScheduleScreen)
ui_Event_Label.set_text("Practice 1")
ui_Event_Label.set_width(lv.SIZE.CONTENT)	# 1
ui_Event_Label.set_height(lv.SIZE.CONTENT)   # 1
ui_Event_Label.set_x(0)
ui_Event_Label.set_y(79)
ui_Event_Label.set_align( lv.ALIGN.CENTER)
ui_Event_Label.set_style_text_color(lv.color_hex(0xFF0101), lv.PART.MAIN | lv.STATE.DEFAULT )
ui_Event_Label.set_style_text_opa(255, lv.PART.MAIN| lv.STATE.DEFAULT )
ui_Event_Label.set_style_text_align( lv.TEXT_ALIGN.CENTER, lv.PART.MAIN | lv.STATE.DEFAULT )
ui_Event_Label.set_style_text_font( font_F1R14, lv.PART.MAIN | lv.STATE.DEFAULT )

ui_Time_Label = lv.label(ui_ScheduleScreen)
ui_Time_Label.set_text("10:14 ")
ui_Time_Label.set_width(lv.SIZE.CONTENT)	# 1
ui_Time_Label.set_height(lv.SIZE.CONTENT)   # 1
ui_Time_Label.set_x(5)
ui_Time_Label.set_y(4)
ui_Time_Label.set_align( lv.ALIGN.CENTER)
ui_Time_Label.set_style_text_color(lv.color_hex(0xFFFFFF), lv.PART.MAIN | lv.STATE.DEFAULT )
ui_Time_Label.set_style_text_opa(255, lv.PART.MAIN| lv.STATE.DEFAULT )
ui_Time_Label.set_style_text_font( font_DISPLAYR60, lv.PART.MAIN | lv.STATE.DEFAULT )

ui_Days = lv.label(ui_ScheduleScreen)
ui_Days.set_text("5")
ui_Days.set_width(lv.SIZE.CONTENT)	# 1
ui_Days.set_height(lv.SIZE.CONTENT)   # 1
ui_Days.set_x(18)
ui_Days.set_y(95)
ui_Days.set_style_text_color(lv.color_hex(0xFFFFFF), lv.PART.MAIN | lv.STATE.DEFAULT )
ui_Days.set_style_text_opa(255, lv.PART.MAIN| lv.STATE.DEFAULT )
ui_Days.set_style_text_align( lv.TEXT_ALIGN.LEFT, lv.PART.MAIN | lv.STATE.DEFAULT )
ui_Days.set_style_text_font( font_DISPLAYM14, lv.PART.MAIN | lv.STATE.DEFAULT )

ui_Hours = lv.label(ui_ScheduleScreen)
ui_Hours.set_text("22")
ui_Hours.set_width(22)
ui_Hours.set_height(10)
ui_Hours.set_x(18)
ui_Hours.set_y(121)
ui_Hours.set_style_text_color(lv.color_hex(0xFFFFFF), lv.PART.MAIN | lv.STATE.DEFAULT )
ui_Hours.set_style_text_opa(255, lv.PART.MAIN| lv.STATE.DEFAULT )
ui_Hours.set_style_text_align( lv.TEXT_ALIGN.LEFT, lv.PART.MAIN | lv.STATE.DEFAULT )
ui_Hours.set_style_text_font( font_DISPLAYM14, lv.PART.MAIN | lv.STATE.DEFAULT )

ui_Minutes = lv.label(ui_ScheduleScreen)
ui_Minutes.set_text("13")
ui_Minutes.set_width(22)
ui_Minutes.set_height(10)
ui_Minutes.set_x(18)
ui_Minutes.set_y(146)
ui_Minutes.set_style_text_color(lv.color_hex(0xFFFFFF), lv.PART.MAIN | lv.STATE.DEFAULT )
ui_Minutes.set_style_text_opa(255, lv.PART.MAIN| lv.STATE.DEFAULT )
ui_Minutes.set_style_text_align( lv.TEXT_ALIGN.LEFT, lv.PART.MAIN | lv.STATE.DEFAULT )
ui_Minutes.set_style_text_font( font_DISPLAYM14, lv.PART.MAIN | lv.STATE.DEFAULT )

ui_Days_Label = lv.label(ui_ScheduleScreen)
ui_Days_Label.set_text("Days")
ui_Days_Label.set_width(lv.SIZE.CONTENT)	# 1
ui_Days_Label.set_height(lv.SIZE.CONTENT)   # 1
ui_Days_Label.set_x(18)
ui_Days_Label.set_y(83)
ui_Days_Label.set_style_text_color(lv.color_hex(0x9E9E9E), lv.PART.MAIN | lv.STATE.DEFAULT )
ui_Days_Label.set_style_text_opa(255, lv.PART.MAIN| lv.STATE.DEFAULT )
ui_Days_Label.set_style_text_align( lv.TEXT_ALIGN.LEFT, lv.PART.MAIN | lv.STATE.DEFAULT )
ui_Days_Label.set_style_text_font( font_DISPLAYM10, lv.PART.MAIN | lv.STATE.DEFAULT )

ui_Hours_Label = lv.label(ui_ScheduleScreen)
ui_Hours_Label.set_text("Hours")
ui_Hours_Label.set_width(lv.SIZE.CONTENT)	# 1
ui_Hours_Label.set_height(lv.SIZE.CONTENT)   # 1
ui_Hours_Label.set_x(18)
ui_Hours_Label.set_y(109)
ui_Hours_Label.set_style_text_color(lv.color_hex(0x9E9E9E), lv.PART.MAIN | lv.STATE.DEFAULT )
ui_Hours_Label.set_style_text_opa(255, lv.PART.MAIN| lv.STATE.DEFAULT )
ui_Hours_Label.set_style_text_align( lv.TEXT_ALIGN.LEFT, lv.PART.MAIN | lv.STATE.DEFAULT )
ui_Hours_Label.set_style_text_font( font_DISPLAYM10, lv.PART.MAIN | lv.STATE.DEFAULT )

ui_Minutes_Label = lv.label(ui_ScheduleScreen)
ui_Minutes_Label.set_text("Mins")
ui_Minutes_Label.set_width(lv.SIZE.CONTENT)	# 1
ui_Minutes_Label.set_height(lv.SIZE.CONTENT)   # 1
ui_Minutes_Label.set_x(19)
ui_Minutes_Label.set_y(135)
ui_Minutes_Label.set_style_text_color(lv.color_hex(0x9E9E9E), lv.PART.MAIN | lv.STATE.DEFAULT )
ui_Minutes_Label.set_style_text_opa(255, lv.PART.MAIN| lv.STATE.DEFAULT )
ui_Minutes_Label.set_style_text_align( lv.TEXT_ALIGN.LEFT, lv.PART.MAIN | lv.STATE.DEFAULT )
ui_Minutes_Label.set_style_text_font( font_DISPLAYM10, lv.PART.MAIN | lv.STATE.DEFAULT )

ui_ScheduleScreen_Container2 = lv.obj(ui_ScheduleScreen)
ui_ScheduleScreen_Container2.remove_style_all()
ui_ScheduleScreen_Container2.set_width(40)
ui_ScheduleScreen_Container2.set_height(40)
ui_ScheduleScreen_Container2.set_x(-27)
ui_ScheduleScreen_Container2.set_y(-53)
ui_ScheduleScreen_Container2.set_align( lv.ALIGN.CENTER)
SetFlag(ui_ScheduleScreen_Container2, lv.obj.FLAG.CLICKABLE, False)
SetFlag(ui_ScheduleScreen_Container2, lv.obj.FLAG.SCROLLABLE, False)
ui_ScheduleScreen_Container2.set_style_radius( 10, lv.PART.MAIN | lv.STATE.DEFAULT )
ui_ScheduleScreen_Container2.set_style_bg_color(lv.color_hex(0x1A1A1A), lv.PART.MAIN | lv.STATE.DEFAULT )
ui_ScheduleScreen_Container2.set_style_bg_opa(255, lv.PART.MAIN| lv.STATE.DEFAULT )

ui_Calendar_Month = lv.label(ui_ScheduleScreen_Container2)
ui_Calendar_Month.set_text("05")
ui_Calendar_Month.set_width(lv.SIZE.CONTENT)	# 1
ui_Calendar_Month.set_height(lv.SIZE.CONTENT)   # 1
ui_Calendar_Month.set_align( lv.ALIGN.CENTER)
ui_Calendar_Month.set_style_text_color(lv.color_hex(0xFFFFFF), lv.PART.MAIN | lv.STATE.DEFAULT )
ui_Calendar_Month.set_style_text_opa(255, lv.PART.MAIN| lv.STATE.DEFAULT )
ui_Calendar_Month.set_style_text_font( font_DISPLAYR30, lv.PART.MAIN | lv.STATE.DEFAULT )

ui_ScheduleScreen_Container3 = lv.obj(ui_ScheduleScreen)
ui_ScheduleScreen_Container3.remove_style_all()
ui_ScheduleScreen_Container3.set_width(40)
ui_ScheduleScreen_Container3.set_height(40)
ui_ScheduleScreen_Container3.set_x(34)
ui_ScheduleScreen_Container3.set_y(-53)
ui_ScheduleScreen_Container3.set_align( lv.ALIGN.CENTER)
SetFlag(ui_ScheduleScreen_Container3, lv.obj.FLAG.CLICKABLE, False)
SetFlag(ui_ScheduleScreen_Container3, lv.obj.FLAG.SCROLLABLE, False)
ui_ScheduleScreen_Container3.set_style_radius( 10, lv.PART.MAIN | lv.STATE.DEFAULT )
ui_ScheduleScreen_Container3.set_style_bg_color(lv.color_hex(0x1A1A1A), lv.PART.MAIN | lv.STATE.DEFAULT )
ui_ScheduleScreen_Container3.set_style_bg_opa(255, lv.PART.MAIN| lv.STATE.DEFAULT )

ui_Calendar_Day = lv.label(ui_ScheduleScreen_Container3)
ui_Calendar_Day.set_text("28")
ui_Calendar_Day.set_width(lv.SIZE.CONTENT)	# 1
ui_Calendar_Day.set_height(lv.SIZE.CONTENT)   # 1
ui_Calendar_Day.set_align( lv.ALIGN.CENTER)
ui_Calendar_Day.set_style_text_color(lv.color_hex(0xFFFFFF), lv.PART.MAIN | lv.STATE.DEFAULT )
ui_Calendar_Day.set_style_text_opa(255, lv.PART.MAIN| lv.STATE.DEFAULT )
ui_Calendar_Day.set_style_text_font( font_DISPLAYR30, lv.PART.MAIN | lv.STATE.DEFAULT )

ui_TelemetryScreen = lv.obj()
SetFlag(ui_TelemetryScreen, lv.obj.FLAG.SCROLLABLE, False)
ui_TelemetryScreen.set_style_bg_color(lv.color_hex(0x000000), lv.PART.MAIN | lv.STATE.DEFAULT )
ui_TelemetryScreen.set_style_bg_opa(255, lv.PART.MAIN| lv.STATE.DEFAULT )

ui_Speed_Arc = lv.arc(ui_TelemetryScreen)
ui_Speed_Arc.set_width(230)
ui_Speed_Arc.set_height(230)
ui_Speed_Arc.set_align( lv.ALIGN.CENTER)
ui_Speed_Arc.set_range(0,360)
ui_Speed_Arc.set_value(280)
ui_Speed_Arc.set_bg_angles(0,280)
ui_Speed_Arc.set_rotation(130)
ui_Speed_Arc.set_style_bg_img_src( ui_images.ui_img_telemety_txt_png, lv.PART.MAIN | lv.STATE.DEFAULT )
ui_Speed_Arc.set_style_arc_color(lv.color_hex(0x3D3D3D), lv.PART.MAIN | lv.STATE.DEFAULT )
ui_Speed_Arc.set_style_arc_opa(200, lv.PART.MAIN| lv.STATE.DEFAULT )
ui_Speed_Arc.set_style_arc_width( 17, lv.PART.MAIN | lv.STATE.DEFAULT )
ui_Speed_Arc.set_style_arc_rounded( False, lv.PART.MAIN | lv.STATE.DEFAULT )

ui_Speed_Arc.set_style_arc_color(lv.color_hex(0x0093CC), lv.PART.INDICATOR | lv.STATE.DEFAULT )
ui_Speed_Arc.set_style_arc_opa(255, lv.PART.INDICATOR| lv.STATE.DEFAULT )
ui_Speed_Arc.set_style_arc_width( 17, lv.PART.INDICATOR | lv.STATE.DEFAULT )
ui_Speed_Arc.set_style_arc_rounded( False, lv.PART.INDICATOR | lv.STATE.DEFAULT )
ui_Speed_Arc.set_style_arc_img_src( ui_images.ui_img_speed_png, lv.PART.INDICATOR | lv.STATE.DEFAULT )

ui_Speed_Arc.set_style_bg_color(lv.color_hex(0xFFFFFF), lv.PART.KNOB | lv.STATE.DEFAULT )
ui_Speed_Arc.set_style_bg_opa(0, lv.PART.KNOB| lv.STATE.DEFAULT )

ui_Throttle_Arc = lv.arc(ui_TelemetryScreen)
ui_Throttle_Arc.set_width(190)
ui_Throttle_Arc.set_height(190)
ui_Throttle_Arc.set_align( lv.ALIGN.CENTER)
ui_Throttle_Arc.set_value(80)
ui_Throttle_Arc.set_bg_angles(0,178)
ui_Throttle_Arc.set_rotation(130)
ui_Throttle_Arc.set_style_arc_color(lv.color_hex(0x3D3D3D), lv.PART.MAIN | lv.STATE.DEFAULT )
ui_Throttle_Arc.set_style_arc_opa(200, lv.PART.MAIN| lv.STATE.DEFAULT )
ui_Throttle_Arc.set_style_arc_width( 20, lv.PART.MAIN | lv.STATE.DEFAULT )
ui_Throttle_Arc.set_style_arc_rounded( False, lv.PART.MAIN | lv.STATE.DEFAULT )

ui_Throttle_Arc.set_style_arc_color(lv.color_hex(0x00FD3B), lv.PART.INDICATOR | lv.STATE.DEFAULT )
ui_Throttle_Arc.set_style_arc_opa(255, lv.PART.INDICATOR| lv.STATE.DEFAULT )
ui_Throttle_Arc.set_style_arc_width( 20, lv.PART.INDICATOR | lv.STATE.DEFAULT )
ui_Throttle_Arc.set_style_arc_rounded( False, lv.PART.INDICATOR | lv.STATE.DEFAULT )
ui_Throttle_Arc.set_style_arc_img_src( ui_images.ui_img_throttle_png, lv.PART.INDICATOR | lv.STATE.DEFAULT )

ui_Throttle_Arc.set_style_bg_color(lv.color_hex(0xFFFFFF), lv.PART.KNOB | lv.STATE.DEFAULT )
ui_Throttle_Arc.set_style_bg_opa(0, lv.PART.KNOB| lv.STATE.DEFAULT )

ui_Brake_Arc = lv.arc(ui_TelemetryScreen)
ui_Brake_Arc.set_width(190)
ui_Brake_Arc.set_height(190)
ui_Brake_Arc.set_align( lv.ALIGN.CENTER)
ui_Brake_Arc.set_value(40)
ui_Brake_Arc.set_bg_angles(0,100)
ui_Brake_Arc.set_mode(ui_Brake_Arc.MODE.REVERSE)
ui_Brake_Arc.set_rotation(310)
ui_Brake_Arc.set_style_arc_color(lv.color_hex(0x3D3D3D), lv.PART.MAIN | lv.STATE.DEFAULT )
ui_Brake_Arc.set_style_arc_opa(200, lv.PART.MAIN| lv.STATE.DEFAULT )
ui_Brake_Arc.set_style_arc_width( 20, lv.PART.MAIN | lv.STATE.DEFAULT )
ui_Brake_Arc.set_style_arc_rounded( False, lv.PART.MAIN | lv.STATE.DEFAULT )

ui_Brake_Arc.set_style_arc_color(lv.color_hex(0x00FD3B), lv.PART.INDICATOR | lv.STATE.DEFAULT )
ui_Brake_Arc.set_style_arc_opa(255, lv.PART.INDICATOR| lv.STATE.DEFAULT )
ui_Brake_Arc.set_style_arc_width( 20, lv.PART.INDICATOR | lv.STATE.DEFAULT )
ui_Brake_Arc.set_style_arc_rounded( False, lv.PART.INDICATOR | lv.STATE.DEFAULT )
ui_Brake_Arc.set_style_arc_img_src( ui_images.ui_img_brake_png, lv.PART.INDICATOR | lv.STATE.DEFAULT )

ui_Brake_Arc.set_style_bg_color(lv.color_hex(0xFFFFFF), lv.PART.KNOB | lv.STATE.DEFAULT )
ui_Brake_Arc.set_style_bg_opa(0, lv.PART.KNOB| lv.STATE.DEFAULT )

ui_Gear = lv.label(ui_TelemetryScreen)
ui_Gear.set_text("N")
ui_Gear.set_width(lv.SIZE.CONTENT)	# 1
ui_Gear.set_height(lv.SIZE.CONTENT)   # 1
ui_Gear.set_x(0)
ui_Gear.set_y(-18)
ui_Gear.set_align( lv.ALIGN.CENTER)
ui_Gear.set_style_text_color(lv.color_hex(0xFFFFFF), lv.PART.MAIN | lv.STATE.DEFAULT )
ui_Gear.set_style_text_opa(255, lv.PART.MAIN| lv.STATE.DEFAULT )
ui_Gear.set_style_text_align( lv.TEXT_ALIGN.CENTER, lv.PART.MAIN | lv.STATE.DEFAULT )
ui_Gear.set_style_text_font( font_DISPLAYB80, lv.PART.MAIN | lv.STATE.DEFAULT )

ui_Gear_Label = lv.label(ui_TelemetryScreen)
ui_Gear_Label.set_text("GEAR")
ui_Gear_Label.set_width(lv.SIZE.CONTENT)	# 1
ui_Gear_Label.set_height(lv.SIZE.CONTENT)   # 1
ui_Gear_Label.set_x(-45)
ui_Gear_Label.set_y(-25)
ui_Gear_Label.set_align( lv.ALIGN.CENTER)
ui_Gear_Label.set_style_text_color(lv.color_hex(0x9E9E9E), lv.PART.MAIN | lv.STATE.DEFAULT )
ui_Gear_Label.set_style_text_opa(255, lv.PART.MAIN| lv.STATE.DEFAULT )
ui_Gear_Label.set_style_text_font( font_DISPLAYM10, lv.PART.MAIN | lv.STATE.DEFAULT )

ui_RPM_Label = lv.label(ui_TelemetryScreen)
ui_RPM_Label.set_text("RPM")
ui_RPM_Label.set_width(lv.SIZE.CONTENT)	# 1
ui_RPM_Label.set_height(lv.SIZE.CONTENT)   # 1
ui_RPM_Label.set_x(0)
ui_RPM_Label.set_y(41)
ui_RPM_Label.set_align( lv.ALIGN.CENTER)
ui_RPM_Label.set_style_text_color(lv.color_hex(0x9E9E9E), lv.PART.MAIN | lv.STATE.DEFAULT )
ui_RPM_Label.set_style_text_opa(255, lv.PART.MAIN| lv.STATE.DEFAULT )
ui_RPM_Label.set_style_text_font( font_DISPLAYM10, lv.PART.MAIN | lv.STATE.DEFAULT )

ui_KHM_Label = lv.label(ui_TelemetryScreen)
ui_KHM_Label.set_text("KHM")
ui_KHM_Label.set_width(lv.SIZE.CONTENT)	# 1
ui_KHM_Label.set_height(lv.SIZE.CONTENT)   # 1
ui_KHM_Label.set_x(43)
ui_KHM_Label.set_y(92)
ui_KHM_Label.set_align( lv.ALIGN.CENTER)
ui_KHM_Label.set_style_text_color(lv.color_hex(0x9E9E9E), lv.PART.MAIN | lv.STATE.DEFAULT )
ui_KHM_Label.set_style_text_opa(255, lv.PART.MAIN| lv.STATE.DEFAULT )
ui_KHM_Label.set_style_text_font( font_DISPLAYM10, lv.PART.MAIN | lv.STATE.DEFAULT )

ui_RPM = lv.label(ui_TelemetryScreen)
ui_RPM.set_text("7463")
ui_RPM.set_width(lv.SIZE.CONTENT)	# 1
ui_RPM.set_height(lv.SIZE.CONTENT)   # 1
ui_RPM.set_x(0)
ui_RPM.set_y(21)
ui_RPM.set_align( lv.ALIGN.CENTER)
ui_RPM.set_style_text_color(lv.color_hex(0xFFFFFF), lv.PART.MAIN | lv.STATE.DEFAULT )
ui_RPM.set_style_text_opa(255, lv.PART.MAIN| lv.STATE.DEFAULT )
ui_RPM.set_style_text_align( lv.TEXT_ALIGN.CENTER, lv.PART.MAIN | lv.STATE.DEFAULT )
ui_RPM.set_style_text_font( font_DISPLAYM24, lv.PART.MAIN | lv.STATE.DEFAULT )

ui_RPM2 = lv.label(ui_TelemetryScreen)
ui_RPM2.set_text("365")
ui_RPM2.set_width(lv.SIZE.CONTENT)	# 1
ui_RPM2.set_height(lv.SIZE.CONTENT)   # 1
ui_RPM2.set_x(0)
ui_RPM2.set_y(93)
ui_RPM2.set_align( lv.ALIGN.CENTER)
ui_RPM2.set_style_text_color(lv.color_hex(0xFFFFFF), lv.PART.MAIN | lv.STATE.DEFAULT )
ui_RPM2.set_style_text_opa(255, lv.PART.MAIN| lv.STATE.DEFAULT )
ui_RPM2.set_style_text_align( lv.TEXT_ALIGN.CENTER, lv.PART.MAIN | lv.STATE.DEFAULT )
ui_RPM2.set_style_text_font( font_DISPLAYM24, lv.PART.MAIN | lv.STATE.DEFAULT )

ui_TelemetryScreen_Container1 = lv.obj(ui_TelemetryScreen)
ui_TelemetryScreen_Container1.remove_style_all()
ui_TelemetryScreen_Container1.set_width(52)
ui_TelemetryScreen_Container1.set_height(20)
ui_TelemetryScreen_Container1.set_x(0)
ui_TelemetryScreen_Container1.set_y(65)
ui_TelemetryScreen_Container1.set_align( lv.ALIGN.CENTER)
SetFlag(ui_TelemetryScreen_Container1, lv.obj.FLAG.CLICKABLE, False)
SetFlag(ui_TelemetryScreen_Container1, lv.obj.FLAG.SCROLLABLE, False)
ui_TelemetryScreen_Container1.set_style_bg_color(lv.color_hex(0xFF0101), lv.PART.MAIN | lv.STATE.DEFAULT )
ui_TelemetryScreen_Container1.set_style_bg_opa(255, lv.PART.MAIN| lv.STATE.DEFAULT )

ui_TelemetryScreen_Label4 = lv.label(ui_TelemetryScreen_Container1)
ui_TelemetryScreen_Label4.set_text("DRS")
ui_TelemetryScreen_Label4.set_width(lv.SIZE.CONTENT)	# 1
ui_TelemetryScreen_Label4.set_height(lv.SIZE.CONTENT)   # 1
ui_TelemetryScreen_Label4.set_align( lv.ALIGN.CENTER)
ui_TelemetryScreen_Label4.set_style_text_color(lv.color_hex(0xFFFFFF), lv.PART.MAIN | lv.STATE.DEFAULT )
ui_TelemetryScreen_Label4.set_style_text_opa(255, lv.PART.MAIN| lv.STATE.DEFAULT )
ui_TelemetryScreen_Label4.set_style_text_font( font_DISPLAYM18, lv.PART.MAIN | lv.STATE.DEFAULT )

ui_RaceScreen = lv.obj()
SetFlag(ui_RaceScreen, lv.obj.FLAG.SCROLLABLE, False)
ui_RaceScreen.set_style_bg_color(lv.color_hex(0x000000), lv.PART.MAIN | lv.STATE.DEFAULT )
ui_RaceScreen.set_style_bg_opa(255, lv.PART.MAIN| lv.STATE.DEFAULT )
ui_RaceScreen.set_style_bg_img_src( ui_images.ui_img_b_png, lv.PART.MAIN | lv.STATE.DEFAULT )

ui_RaceScreen.set_style_bg_img_src( ui_images.TemporaryImage, lv.PART.SCROLLBAR | lv.STATE.DEFAULT )

lv.scr_load(ui_MsgScreen)
