# This file was generated by SquareLine Studio
# SquareLine Studio version: SquareLine Studio 1.4.0
# LVGL version: 8.3.11
# Project name: SquareLine_Project


def play_emil(event_struct):
    return


def play_emoil(event_struct):
    return


